services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: stock_price
      MYSQL_USER: stock_price_user
      MYSQL_PASSWORD: stock_price_password
      MYSQL_ROOT_PASSWORD: stock_price_password  # ルートパスワードを設定
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # 空のパスワードを許可しない
    healthcheck:  # ヘルスチェックの設定
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "stock_price_user", "-pstock_price_password"]
      interval: 15s
      timeout: 10s
      retries: 51
    volumes:
      - mysql_data:/var/lib/mysql  # データ永続化のためのボリュームマウント

  web:
    build: 
      context: .
      target: development
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      DB_HOST: db
    volumes:
      - .:/code  # マウントポイントを更新
    ports:
      - "8000:8000"
    links:
      - db  # dbサービスへのリンクを追加
    depends_on:  # dbサービスの起動を待機
      db:
        condition: service_healthy  # ヘルスチェックを追加

volumes:
  mysql_data:  # ボリューム名を保持